import raw from "@/data/questions.json";
import type { ModuleNode, Question } from "./types";

// The JSON is generated by scripts/extract.py from the source PDFs.
export const QUESTIONS = raw as Question[];

/** Build the module → section tree with counts, preserving source order. */
export function buildTree(questions: Question[] = QUESTIONS): ModuleNode[] {
  const modules: ModuleNode[] = [];
  for (const q of questions) {
    let m = modules.find((x) => x.module === q.module);
    if (!m) {
      m = { module: q.module, count: 0, sections: [] };
      modules.push(m);
    }
    m.count++;
    let s = m.sections.find((x) => x.section === q.section);
    if (!s) {
      s = { section: q.section, count: 0 };
      m.sections.push(s);
    }
    s.count++;
  }
  return modules;
}

export const TREE = buildTree();
export const MODULES = TREE.map((m) => m.module);

export function getQuestion(id: string): Question | undefined {
  return QUESTIONS.find((q) => q.id === id);
}
